
define(function() {
  var Bubble;
  return Bubble = (function() {

    Bubble.prototype.x = 0;

    Bubble.prototype.y = 0;

    Bubble.prototype.dx = 0;

    Bubble.prototype.lifetime = 0;

    Bubble.prototype.PI2 = 2 * Math.PI;

    Bubble.prototype.draw = function() {
      var ac;
      ac = atom.context;
      ac.globalAlpha = 0.5;
      ac.fillStyle = '#A2CBF5';
      ac.beginPath();
      ac.arc(this.x - this.r_2 + this.dx, this.y - this.r_2, this.r, 0, this.PI2);
      ac.closePath();
      ac.fill();
      return ac.globalAlpha = 1;
    };

    Bubble.prototype.move = function() {
      if (this.y < -this.r_2 || this.x < -this.r_2) {
        return this.move = null;
      } else {
        this.y += this.dy;
        this.x += 4 * this.game.current;
        this.dx = this.dxAmplitude * Math.sin(this.lifetime);
        return this.lifetime += 0.2;
      }
    };

    function Bubble(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
      this.r = $$.R(1, 5) + $$.r(5);
      this.r_2 = this.r >> 1;
      this.dy = -$$.r(2.9) - 0.85;
      this.dxAmplitude = $$.r(3) + 1;
    }

    return Bubble;

  })();
});

// Generated by CoffeeScript 1.5.0-pre
