// Generated by CoffeeScript 1.4.0

define(function() {
  var Hook;
  return Hook = (function() {

    Hook.prototype.x = 0;

    Hook.prototype.y = 0;

    Hook.prototype.lifetime = 0;

    Hook.prototype.HOOKANGLE = 3.6185837;

    Hook.prototype.draw = function() {
      var ac;
      ac = atom.context;
      if (false) {
        return ac.drawImage(atom.gfx.bubble, this.x - this.w_2 + this.dx, this.y - this.h_2);
      } else {
        ac.save();
        ac.lineWidth = this.r * 0.25;
        ac.strokeStyle = '#111';
        ac.translate(this.x, this.y);
        ac.beginPath();
        ac.arc(0, 0, this.r, 0, this.HOOKANGLE);
        ac.stroke();
        ac.moveTo(this.r, 0);
        ac.quadraticCurveTo(this.r * 0.3, -this.r * 1.6, this.r * 0.3, -2 * this.r);
        ac.stroke();
        ac.lineWidth = 0.5;
        ac.strokeStyle = '#222';
        ac.moveTo(this.r * 0.3, -2 * this.r);
        ac.lineTo(this.r * 0.3, -this.y);
        ac.stroke();
        return ac.restore();
      }
    };

    Hook.prototype.move = function() {
      if (this.y < -this.r_2 || this.x < -this.r_2) {
        return this.move = null;
      } else {
        return this.x += 2 * this.game.current;
      }
    };

    function Hook(params) {
      var k, v;
      for (k in params) {
        v = params[k];
        this[k] = v;
      }
      this.r = $$.R(3, 8);
      this.r_2 = this.r >> 1;
    }

    return Hook;

  })();
});
