// Generated by CoffeeScript 1.4.0

define(['core/util', 'core/atom', 'core/game'], function(_util, _atom, FishGame) {
  var isPreloadComplete, loaded, startGame;
  startGame = function() {
    window.game = new FishGame();
    return window.game.run();
  };
  loaded = {
    gfx: false,
    sfx: false
  };
  isPreloadComplete = function() {
    if (loaded.gfx && loaded.sfx) {
      startGame();
      return true;
    } else {
      return false;
    }
  };
  atom.preloadImages({
    icon: 'icon.png',
    fish: 'fish.jpg',
    bubble: 'b0_0.png'
  }, function() {
    loaded.gfx = true;
    return isPreloadComplete();
  });
  atom.preloadSounds({
    tick: 'tick.mp3',
    plankton1: 'plankton1.mp3',
    plankton2: 'plankton2.mp3',
    plankton3: 'plankton3.mp3',
    recruit: 'recruit.mp3'
  }, function() {
    loaded.sfx = true;
    return isPreloadComplete();
  });
});
