// Generated by CoffeeScript 1.4.0

define(['core/util', 'core/atom', 'core/game'], function(_util, _atom, FishGame) {
  var isPreloadComplete, loaded, startGame;
  startGame = function() {
    window.game = new FishGame();
    return window.game.run();
  };
  loaded = {
    gfx: false,
    sfx: false
  };
  isPreloadComplete = function() {
    if (loaded.gfx && loaded.sfx) {
      startGame();
      return true;
    } else {
      return false;
    }
  };
  atom.preloadImages({
    icon: 'icon.png',
    fledgeling0: 'fledgeling0.png',
    fledgeling1: 'fledgeling1.png',
    bubble0n1: 'bubble0/1.png',
    bubble0n2: 'bubble0/2.png',
    bubble0n3: 'bubble0/3.png',
    bubble0n4: 'bubble0/4.png',
    bubble0n5: 'bubble0/5.png',
    bubble0n6: 'bubble0/6.png',
    bubble1n1: 'bubble1/1.png',
    bubble1n2: 'bubble1/2.png',
    bubble1n3: 'bubble1/3.png',
    bubble1n4: 'bubble1/4.png',
    bubble1n5: 'bubble1/5.png',
    bubble1n6: 'bubble1/6.png'
  }, function() {
    loaded.gfx = true;
    return isPreloadComplete();
  });
  atom.preloadSounds({
    tick: 'tick.mp3',
    plankton1: 'plankton1.mp3',
    plankton2: 'plankton2.mp3',
    plankton3: 'plankton3.mp3',
    recruit: 'recruit.mp3'
  }, function() {
    loaded.sfx = true;
    return isPreloadComplete();
  });
});
